### ISSUE TITLE
FE - "suggest a guest" input fields

### ISSUE THREAD

**Issue by emalineg** [emalineg/esportsconnection-fe#2]
input fields for suggest a guest component:

- guest name (string)
- guest contact (string)
- submitters name (optional, string)
- submitters contact (optional, string)
- what impact have they had on the world of esports? (text)

**Comment by LizAinslie** [comment]
some of my most satisfying work tbh 
![mobile screenshot](https://i-work-at-the.cocaine.institute/Lizzy649bf3e8yUDeef0leWaO.png)
![desktop screenshot](https://i-work-at-the.cocaine.institute/Lizzy649bf40cgksCZTPtJTp7.png)
